version: "3.7"

services:
  proxy:
    container_name: crm-proxy
    image: nginx:mainline-alpine3.18-slim
    ports:
      - 3500:80
    volumes:
      - ../:/var/www/myapp
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - mariadb

  php:
    container_name: crm-php
    image: php:8.2.12-fpm-alpine3.18
    depends_on:
      - mariadb

  phpmyadmin:
    container_name: crm-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  mariadb:
    container_name: crm-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: DevelopmentPassword
volumes:
  mariadb-data:
